{{- if .Values.secrets.enabled }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ .Values.secrets.list }}
spec:
  provider: gke
  parameters:
    secrets:
{{- range $secret := .Values.secrets.list  }}
      - resourceName: "projects/{{ .Values.secrets.projectId }}/secrets/{{ $secret.name }}/versions/{{ $secret.version }}"
        path: ".env"
{{- end }}
{{- end }}