{{- if .Values.secrets.enabled }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ .Release.Name }}
spec:
  provider: gke
  parameters:
    secrets:
{{- range .Values.secrets.list  }}
      - resourceName: "projects/{{ $.Values.secrets.projectId }}/secrets/{{ .name }}/versions/{{ .version }}"
        path: ".env"
{{- end }}
{{- end }}