name: Build and deploy to GKE

on:
  push:
    branches:
      - develop
      - homolog
      - main

jobs:
  deploy_gke:
    name: Build and push docker image do Docker Hub
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name }}
    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      CONTAINER_REGISTRY: ${{ secrets.DOCKERHUB_USERNAME }}
      GKE_PROJECT: ${{ secrets.GKE_PROJECT }}
      GKE_SA_KEY: ${{ secrets.GKE_SA_KEY }}
      GKE_CLUSTER: ${{ vars.GKE_CLUSTER }}
      GKE_LOCATION: ${{ vars.GKE_LOCATION }}
    steps:
      - name: Set repo name env variable
        id: getRepoName
        shell: bash
        run: |-
          REPO_NAME=$(echo ${{ github.repository }} | cut -d '/' -f 2)
          echo "REPO_NAME=$REPO_NAME" >> $GITHUB_ENV

      - name: Checkout to repository content
        uses: actions/checkout@v4

      - name: Build image
        run: |-
          docker build \
            -t ${{ env.CONTAINER_REGISTRY }}/${{ env.REPO_NAME }}:${{ github.sha }} \
            -t ${{ env.CONTAINER_REGISTRY }}/${{ env.REPO_NAME }}:latest .

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_TOKEN }}

      - name: Push image to Docker Hub
        run: |-
          docker push ${{ env.CONTAINER_REGISTRY }}/${{ env.REPO_NAME }}:${{ github.sha }}
          docker push ${{ env.CONTAINER_REGISTRY }}/${{ env.REPO_NAME }}:latest

      - name: Auth to gcp
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ env.GKE_SA_KEY }}

      - name: Connect to GKE cluster
        uses: google-github-actions/get-gke-credentials@v2
        with:
          cluster_name: ${{ env.GKE_CLUSTER }}
          location: ${{ env.GKE_LOCATION }}

      - name: Install helm chart on cluster
        run: |-
          helm upgrade -n ${{ env.REPO_NAME }} ${{ env.REPO_NAME }} ./helm \
            -f ./helm-values.yaml \
            --install \
            --create-namespace \
            --atomic \
            --timeout 4m \
            --set containers.app.image="${{ env.CONTAINER_REGISTRY }}/${{ env.REPO_NAME }}:${{ github.sha }}"
